Run tests on chrome instead of electron
This avoid the error:

[ERROR:trust_store_mac.cc(844)] Error parsing certificate:
ERROR: Failed parsing certificate policies

When running the tests on OSX.